# Generated by Django 3.1.7 on 2021-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50,
                 unique=True, verbose_name='name')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='created_at')),
            ],
        ),
    ]
