# Generated by Django 3.1.7 on 2021-03-28 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('labels', '0001_initial'),
        ('statuses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(
                    max_length=200,
                    verbose_name='name'
                )),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(
                    auto_now_add=True, verbose_name='created_at')),
                ('author', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='author',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='author'
                )),
                ('executor', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='executor',
                    to=settings.AUTH_USER_MODEL,
                    verbose_name='user'
                )),
            ],
        ),
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.AutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(
                    on_delete=django.db.models.deletion.PROTECT,
                    related_name='label',
                    to='labels.label',
                    verbose_name='label'
                )),
                ('task', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='task',
                    to='tasks.task',
                    verbose_name='task'
                )),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(
                related_name='labels',
                through='tasks.TaskLabel',
                to='labels.Label',
                verbose_name='labels'
            ),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name='status',
                to='statuses.status',
                verbose_name='status'
            ),
        ),
    ]
